name: CI
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ls -la  
          
  # build-linux:
    # name: Build (Linux)
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@v3
      # - name: Build
        # run: |
          # chmod +x ${{ github.workspace }}/*.bash
          # ${{ github.workspace }}/createDebFromSourceUbuntu.bash --deps-only
          # ${{ github.workspace }}/bootStrap.bash --with-system-libass 
  build-windows:
    name: Build (Windows)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt-get install autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libclang-dev libgdk-pixbuf2.0-dev libltdl-dev libgl-dev libpcre2-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full patch perl python3 python3-mako python3-packaging python3-pkg-resources python3-setuptools python-is-python3 ruby sed sqlite3 unzip wget xz-utils
          git clone git@github.com:mxe/mxe.git
          cd mxe
          make -j4        
##bash stuff 
         ##chmod +x ${{ github.workspace }}/*.sh
         ##sh ${{ github.workspace }}/bootStrapCrossMingwQt6_mxe.sh 
         
  # build-macos:
    # name: Build (macOS)
    # runs-on: macos-latest
    # steps:
      # - uses: actions/checkout@v3
      # - name: Build
        # run: |
          # chmod +x ${{ github.workspace }}/*.bash
          # brew install cmake nasm yasm qt xvid x264 x265 libvpx aom opus fdk-aac lame libass mp4v2 a52dec
          # export MACOSX_DEPLOYMENT_TARGET=$(xcrun --sdk macosx --show-sdk-version)
          # bash ${{ github.workspace }}/bootStrapOsx_Catalina.bash --enable-qt6
